#!/usr/bin/env python
import sys
import zarafa_search

if __name__ == '__main__':
    sys.exit(zarafa_search.main())



# flow:
#
#  Service.incremental_sync
#   calls server.sync()
#    calls for every change:
#      ServerImporter.update()
#       enqueues changes
# -changes via iqueue--->Indexworker-->
