#!/usr/bin/env python
import sys
import zarafa_search

if __name__ == '__main__':
    sys.exit(zarafa_search.main())



# flow:
#
# Service.main()
#
#  Service.initial_sync (first time only)
#   equeues all folders to iqueue
#   waits for processing to be complete

#
#  Service.incremental_sync (main process)
#   calls server.sync()
#    calls for every folder change:
#      ServerImporter.update()
#       enqueues changed folders to iqueue
#       waits for processing to be complete
#   loop
#
#  IndexWorker (1 one more subprocesses)
#   dequeues changed folders from iqueue
#    calls folder.sync() for every folder
#     calls FolderUpdater.update() for every update
